import { Student } from '../models/student.class';

export const STUDENTS: Array<Student> = [
  new Student({
    name: 'Alessandro',
    surname: 'Ciapponi',
    gender: 'M',
    age: 25,
    location: {
      postalCode: '00000',
      city: 'Milano',
      address: '',
      state: 'Lombardia',
      country: 'Italia',
    },
    hobbies: [
      { name: 'Calishenics', icon: '' },
      { name: 'Gaming', icon: '' },
    ],
    pets: [],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Chiara',
    surname: 'Orrigo',
    gender: 'F',
    age: 25,
    location: {
      postalCode: '00000',
      city: 'Napoli',
      address: '',
      state: 'Campania',
      country: 'Italia',
    },
    hobbies: [
      { name: 'musica', icon: '' },
      { name: 'film', icon: '' },
    ],
    pets: [
      { name: 'bobby', type: 'dog', breed: 'carlino', gender: 'M', age: 1 },
    ],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Isabella',
    surname: 'Marini',
    gender: 'F',
    age: 22,
    location: {
      postalCode: '00000',
      city: 'Aquila',
      address: '',
      state: 'Abruzzo',
      country: 'Italia',
    },
    hobbies: [
      { name: 'musica', icon: '' },
      { name: 'leggere', icon: '' },
      { name: 'film', icon: '' },
    ],
    pets: [
      { name: 'bobby', type: 'dog', breed: 'carlino', gender: 'M', age: 1 },
    ],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Manuel',
    surname: 'Luppino',
    gender: 'M',
    age: 28,
    location: {
      postalCode: '00000',
      city: 'Palermo',
      address: '',
      state: 'Sicilia',
      country: 'Italia',
    },
    hobbies: [
      { name: 'calcio', icon: '' },
      { name: 'musica', icon: '' },
      { name: 'videogiochi', icon: '' },
    ],
    pets: [],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
      { name: 'spagnolo', icon: 'es' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Dennis',
    surname: 'Bucca',
    gender: 'M',
    age: 23,
    location: {
      postalCode: '00000',
      city: 'Palermo',
      address: '',
      state: 'Sicilia',
      country: 'Italia',
    },
    hobbies: [
      { name: 'calcio', icon: '' },
      { name: 'palestra', icon: '' },
    ],
    pets: [],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Nicholas',
    surname: 'Braccaioli',
    age: 23,
    gender: 'M',
    location: {
      postalCode: '00000',
      city: 'Milano',
      address: '',
      state: 'Lombardia',
      country: 'Italia',
    },
    hobbies: [
      { name: 'calcio', icon: '' },
      { name: 'palestra', icon: '' },
    ],
    pets: [
      { name: 'bobby', type: 'dog', breed: 'carlino', gender: 'M', age: 1 },
    ],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Elena',
    surname: 'Durante',
    gender: 'F',
    age: 22,
    location: {
      postalCode: '00000',
      city: 'Palermo',
      address: '',
      state: 'Sicilia',
      country: 'Italia',
    },
    hobbies: [
      { name: 'musica', icon: '' },
      { name: 'serie tv', icon: '' },
    ],
    pets: [
      { name: 'bobby', type: 'dog', breed: 'carlino', gender: 'M', age: 1 },
    ],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Marika',
    surname: 'Nese',
    gender: 'F',
    age: 21,
    location: {
      postalCode: '00000',
      city: 'Venezia',
      address: '',
      state: 'Veneto',
      country: 'Italia',
    },
    hobbies: [
      { name: 'sport', icon: '' },
      { name: 'viaggiare', icon: '' },
      { name: 'scoprire la natura', icon: '' },
    ],
    pets: [
      { name: 'bobby', type: 'dog', breed: 'carlino', gender: 'M', age: 1 },
    ],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
      { name: 'spagnolo', icon: 'es' },
      { name: 'tedesco', icon: 'de' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Albi',
    surname: 'Spahiu',
    gender: 'M',
    age: 25,
    location: {
      postalCode: '00000',
      city: 'Bologna',
      address: '',
      state: 'Emilia Romagna',
      country: 'Italia',
    },
    hobbies: [
      { name: 'scacchi', icon: '' },
      { name: 'cinema', icon: '' },
      { name: 'serie tv', icon: '' },
      { name: 'corsa', icon: '' },
    ],
    pets: [],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
      { name: 'albanese', icon: 'al' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Valentina',
    surname: 'Beltrame',
    gender: 'F',
    age: 23,
    location: {
      postalCode: '00000',
      city: 'Venezia',
      address: '',
      state: 'Veneto',
      country: 'Italia',
    },
    hobbies: [{ name: 'leggere', icon: '' }],
    pets: [],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
      { name: 'francese', icon: 'fr' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Emanuela',
    surname: 'Fiorillo',
    gender: 'F',
    age: 24,
    location: {
      postalCode: '00000',
      city: 'Napoli',
      address: '',
      state: 'Campania',
      country: 'Italia',
    },
    hobbies: [
      { name: 'film', icon: '' },
      { name: 'piano', icon: '' },
    ],
    pets: [
      { name: 'bobby', type: 'dog', breed: 'carlino', gender: 'M', age: 1 },
    ],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Giovanni',
    surname: 'Alessi',
    gender: 'M',
    age: 22,
    location: {
      postalCode: '00000',
      city: 'Torino',
      address: '',
      state: 'Piemonte',
      country: 'Italia',
    },
    hobbies: [
      { name: 'leggere', icon: '' },
      { name: 'film', icon: '' },
    ],
    pets: [],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Ilyass',
    surname: 'Bermaki',
    gender: 'M',
    age: 22,
    location: {
      postalCode: '00000',
      city: 'Torino',
      address: '',
      state: 'Piemonte',
      country: 'Italia',
    },
    hobbies: [
      { name: 'videogiochi', icon: '' },
      { name: 'basketball', icon: '' },
    ],
    pets: [
      { name: 'bobby', type: 'dog', breed: 'carlino', gender: 'M', age: 1 },
    ],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
      { name: 'arabo', icon: 'sa' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Santino',
    surname: 'Di Gennaro',
    gender: 'M',
    age: 26,
    location: {
      postalCode: '00000',
      city: 'Palermo',
      address: '',
      state: 'Siclia',
      country: 'Italia',
    },
    hobbies: [
      { name: 'lettura', icon: '' },
      { name: 'videogiochi', icon: '' },
      { name: 'film', icon: '' },
    ],
    pets: [],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
  new Student({
    name: 'Marco',
    surname: 'Esu',
    gender: 'M',
    age: 31,
    location: {
      postalCode: '00000',
      city: 'Cagliari',
      address: '',
      state: 'Sardegna',
      country: 'Italia',
    },
    hobbies: [
      { name: 'lettura', icon: '' },
      { name: 'videogiochi', icon: '' },
      { name: 'film', icon: '' },
    ],
    pets: [],
    knownLanguages: [
      { name: 'italiano', icon: 'it' },
      { name: 'inglese', icon: 'gb' },
    ],
    jobExperiences: [],
    resonance: { likes: 0, dislikes: 0 },
  }),
];
